### ISSUE TITLE
rocksdb.cr does not seem to work on M1 Macs with Crystal 1.2.2

### ISSUE THREAD

**Issue by peterschols** [maiha/rocksdb.cr#6]
When running on a MacBook Pro M1 Max:
```
brew install rocksdb
shards install
crystal build --release test/test.cr
```

The following error is thrown:
```
ld: library not found for -lrocksdb (this usually means you need to install the development package for librocksdb)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/peter/apps/test/test  -rdynamic -L/Users/peter/.asdf/installs/crystal/1.2.2/embedded/lib -lrocksdb -lpcre -lgc -lpthread -levent -liconv -ldl`
```

**Comment by maiha** [comment]
Hi, @peterschols 

This library requires `librocksdb.a` for static linking. Please make sure you have that file installed in your environment.

I don't know about MacOS, but it would be `librocksdb` or some stuff rather than `rocksdb`.

**Comment by peterschols** [comment]
@maiha many thanks for your answer, much appreciated!

**Comment by jolly336** [comment]
@peterschols  Mac install: `brew install rocksdb` 

detail see: https://github.com/facebook/rocksdb/blob/main/INSTALL.md
