### ISSUE TITLE
Iterator memory leak

### ISSUE THREAD

**Issue by notramo** [maiha/rocksdb.cr#7]
The iterator solution is not idiomatic Crystal. From the README:
```crystal
iter = db.new_iterator
iter.key           # => "k0"
iter.next
iter.value         # => "1"
iter.first
iter.key           # => "k0"
iter.seek("k2")
iter.next
iter.valid?        # => false

iter.close  # memory leaks when you forget this
```
There is a convention for doing it in Crystal: accepting a block, and using `ensure`:
```crystal 
def iterate
  iterator = db.new_iterator
  yield iterator
ensure
  # Close it if not Nil
  iterator.try &.close
end
```
Then it could be used like this:
```crystal
database.iterate do |iter|
  iter.next
  iter.valid?
  # etc.
end
```

Even better solution would be to use the [Iterator](https://crystal-lang.org/api/1.5.0/Iterator.html) from the stdlib:
```crystal
class RocksDB::Iterator
  include Iterator

  @iterator = db.new_iterator

  def finalize
    @iterator.close
  end

  def next
    # end the iteration using the `stop` method if there are no items left
    stop if ! iterator.valid?

    # return the next item
    return @iterator.next
  end
end
```
How to use:
```crystal
# db.iterator should return a new RocksDB::Iterator
iterator = db.iterator
iterator.each do |i|
  puts i
end
```

**Comment by bendangelo** [comment]
Can these changes be added? I feel it's a great improvement.

**Comment by maiha** [comment]
@bendangelo 
Sorry I missed it and have not been able to reply for a long time.

Iterations that guarantee close are already defined as `each`. Please check if this satisfies your purpose.
https://github.com/maiha/rocksdb.cr/blob/main/src/rocksdb/commands/iteration.cr#L12-L21

**Comment by bendangelo** [comment]
ok thanks.

**Comment by bendangelo** [comment]
I think this can be closed? .each works
